### ISSUE TITLE
'Unable to read beyond the end of the stream'

### ISSUE THREAD

**Issue by ghost** [Marlamin/WorldMapCompiler#1]
Hi Marlamin, running the WorldMapCompiler program i encounter this error:
Exception thrown: 'System.IO.EndOfStreamException' in System.Private.CoreLib.dll An unhandled exception of type 'System.IO.EndOfStreamException' occurred in System.Private.CoreLib.dll Unable to read beyond the end of the stream.
There's a way to fix this? (I'm a noob with Visual Studio and C#).
![Untitled](https://user-images.githubusercontent.com/56413236/133161053-d2b5cef5-dc7d-4f06-bd2c-b9fb7c4e4345.png)

**Comment by Marlamin** [comment]
This should be fixed by updating to a newer version of CASCLib in all the projects (commited), but sadly that will likely need you to fix some of the references manually which might be annoying to do for someone unfamiliar with VS. I've uploaded a precompiled release that might work better out of the box: https://github.com/Marlamin/WorldMapCompiler/releases/tag/v0.1-alpha
